/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /* eslint-disable */

/******************************************************************************************
 * Do not edit this file manually.
 * Automatically generated via `qing sod app`.
 * See `lib/dev/sod/objects/app.yaml` for details.
 ******************************************************************************************/

export interface MainPageUserState {
  id?: string;
  name?: string;
  url?: string;
  iconUrl?: string;
  admin?: boolean;
}

export interface MainPageStateData {
  user?: MainPageUserState;
  postPerm?: number;
  forums?: boolean;
}
