/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /* eslint-disable */

/******************************************************************************************
 * Do not edit this file manually.
 * Automatically generated via `qing sod auth`.
 * See `lib/dev/sod/objects/auth.yaml` for details.
 ******************************************************************************************/

export interface User {
  id: string;
  name: string;
  link: string;
  iconURL: string;
  admin?: boolean;
}
