/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /* eslint-disable */

/******************************************************************************************
 * Do not edit this file manually.
 * Automatically generated via `qing sod cmt`.
 * See `lib/dev/sod/objects/cmt.yaml` for details.
 ******************************************************************************************/

import { CmtResult } from '../da/types.js';

export interface Cmt extends CmtResult {
  id: string;
  userID?: string;
  userURL: string;
  userIconURL: string;
  createdAt: string;
  modifiedAt: string;
  parentID?: string;
}

export interface CmtFocusModeData {
  is404?: boolean;
  cmt?: Cmt;
  parentCmt?: Cmt;
}
