/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /* eslint-disable */

/******************************************************************************************
 * Do not edit this file manually.
 * Automatically generated via `qing sod post`.
 * See `lib/dev/sod/objects/post.yaml` for details.
 ******************************************************************************************/

import { CmtFocusModeData } from './cmt.js';

export interface PostPageState {
  id: string;
  cmtCount?: number;
  initialLikes?: number;
  initialHasLiked?: boolean;
  isThread?: boolean;
  forumID?: string;
  focusMode?: CmtFocusModeData;
}

export interface PostCorePayload {
  html: string;
  title?: string;
  src?: string;
  summary?: string;
  brTime?: string;
}
