/* eslint-disable */

/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
  * Do not edit this file manually.
  * Automatically generated via `qing sod app/appRawSettings`.
  * See `lib/dev/sod/objects/app/appRawSettings.yaml` for details.
  ******************************************************************************************/

export interface AppRawSettings {
  community?: CommunityRawSettings;
}

export interface CommunityRawSettings {
  queAndDis?: boolean;
  forums?: boolean;
  forumGroups?: boolean;
}
