/*
* Copyright (C) The Qing Project. All rights reserved.
*
* Use of this source code is governed by a license that
* can be found in the LICENSE file.
*/

 /******************************************************************************************
* This code was automatically generated by `@qing/def`.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/package def

const minUserPwdLenMinUserPwdLen = 6
const maxUserPwdLenMaxUserPwdLen = 30
const maxCaptchaLenMaxCaptchaLen = 10
const maxGenericStringLenMaxGenericStringLen = 100
const errInvalidUserOrPwdErrInvalidUserOrPwd = 1
const errCannotSetAdminOfYourselfErrCannotSetAdminOfYourself = 1
const errAlreadyAdminErrAlreadyAdmin = 2
const columnCreatedColumnCreated = "createdAt"
const columnLikesColumnLikes = "likes"
const columnCommentsColumnComments = "comments"
const columnMessagesColumnMessages = "messages"
const routeUserRouteUser = "u"
const routePostRoutePost = "p"
const routeAuthRouteAuth = "auth"
const routeDevPageRouteDevPage = "__"
const routeMRouteM = "m"
const routeMXRouteMX = "mx"
const routeAPIRouteAPI = "s"
const routeForumRouteForum = "f"
const routeDiscussionRouteDiscussion = "d"
const routeForumGroupRouteForumGroup = "g"
const routeQuestionRouteQuestion = "q"
const routeAnswerRouteAnswer = "a"
const routeLangRouteLang = "lang"
const entityPostEntityPost = 1
const entityCmtEntityCmt = 2
const entityDiscussionEntityDiscussion = 4
const entityQuestionEntityQuestion = 5
const entityDiscussionMsgEntityDiscussionMsg = 6
const entityAnswerEntityAnswer = 7
const entityForumDiscussionEntityForumDiscussion = 8
const entityForumQuestionEntityForumQuestion = 9
const entityForumEntityForum = 10
const entityForumGroupEntityForumGroup = 11
const errGenericErrGeneric = 10000
const errNeedAuthErrNeedAuth = 10001
const errCaptchaNotFoundErrCaptchaNotFound = 10002
const errCaptchaNotMatchErrCaptchaNotMatch = 10003
const errPermissionDeniedErrPermissionDenied = 10004
const errResourceNotFoundErrResourceNotFound = 10005
const keyPostsKeyPosts = "posts"
const keyDiscussionsKeyDiscussions = "discussions"
const keyAnswersKeyAnswers = "answers"
const keyPageKeyPage = "page"
const keyPageSizeKeyPageSize = "pageSize"
const keyTabKeyTab = "tab"
const keyValueKeyValue = "value"
const keyQuestionsKeyQuestions = "questions"
const keyCommunitySettingsKeyCommunitySettings = "communitySettings"
const keyLangKeyLang = "lang"
const forumStatusOpenForumStatusOpen = 0
const forumStatusArchivedForumStatusArchived = 1
const upVoteValueUpVoteValue = 1
const downVoteValueDownVoteValue = -1
const noVoteValueNoVoteValue = 0
const maxTitleLenMaxTitleLen = 200
const maxEmailLenMaxEmailLen = 200
const maxNameLenMaxNameLen = 100
const maxFileNameLenMaxFileNameLen = 255
const maxUserInfoFieldLenMaxUserInfoFieldLen = 100
const maxURLLenMaxURLLen = 200
const maxPwdHashLenMaxPwdHashLen = 255
const formUploadMainFormUploadMain = "main"
const deleteFlagAuthorDeleteFlagAuthor = 1
const deleteFlagHostDeleteFlagHost = 2
