/******************************************************************************************
* This code was automatically generated by go-const-gen.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/

package undefined

// DbType ...
type DbType struct {
	CmtHostAnswer int
	CmtHostDiscussion int
	CmtHostPost int
	CmtHostQuestion int
	ThreadTypeDiscussion int
	ThreadTypePost int
	ThreadTypeQuestion int
}

// Db ...
var Db *DbType

func init() {
	Db = &DbType{
		CmtHostAnswer: 4,
		CmtHostDiscussion: 3,
		CmtHostPost: 1,
		CmtHostQuestion: 2,
		ThreadTypeDiscussion: 3,
		ThreadTypePost: 1,
		ThreadTypeQuestion: 2,
	}
}
