/*
* Copyright (C) The Qing Project. All rights reserved.
*
* Use of this source code is governed by a license that
* can be found in the LICENSE file.
*/

 /******************************************************************************************
* This code was automatically generated by `@qing/def`.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/package def

const threadTypePostThreadTypePost = 1
const threadTypeQuestionThreadTypeQuestion = 2
const threadTypeDiscussionThreadTypeDiscussion = 3
const cmtHostPostCmtHostPost = 1
const cmtHostQuestionCmtHostQuestion = 2
const cmtHostDiscussionCmtHostDiscussion = 3
const cmtHostAnswerCmtHostAnswer = 4
