/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /* eslint-disable */

/******************************************************************************************
 * Do not edit this file manually.
 * Automatically generated via `qing sod profile/profileLang`.
 * See `lib/dev/sod/objects/profile/profileLang.yaml` for details.
 ******************************************************************************************/

export interface ProfileLang {
  id?: string;
  name?: string;
  localizedName?: string;
}

export interface GetProfileLangResult {
  userLang?: string;
  langs?: ProfileLang[];
}
