/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
  * Do not edit this file manually.
  * Automatically generated via `qing sod dev/auth/tUserInfo`.
  * See `lib/dev/sod/objects/dev/auth/tUserInfo.yaml` for details.
  ******************************************************************************************/

package tUserInfo

type TUserInfo struct {
	ID       string `json:"id"`
	Name     string `json:"name,omitempty"`
	IconName string `json:"iconName,omitempty"`
	Admin    bool   `json:"admin,omitempty"`
}

func NewTUserInfo(id string, name string, iconName string, admin bool) TUserInfo {
	return TUserInfo{
		ID: id,
		Name: name,
		IconName: iconName,
		Admin: admin,
	}
}
