/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
  * Do not edit this file manually.
  * Automatically generated via `qing sod cmt/cmt`.
  * See `lib/dev/sod/objects/cmt/cmt.yaml` for details.
  ******************************************************************************************/

package cmtSod

import (
  	"qing/da"
	contentBaseSod "qing/sod/contentBase"
)

type Cmt struct {
	da.CmtResult
	contentBaseSod.ContentBaseModelBase

	EID      string  `json:"id,omitempty"`
	UserEID  string  `json:"userEID,omitempty"`
	ParentID *string `json:"parentID,omitempty"`
}

func NewCmt(cmtResult *da.CmtResult, contentBaseModelBase *contentBaseSod.ContentBaseModelBase, id string, userEID string, parentID *string) Cmt {
	return Cmt{
		CmtResult: *cmtResult,
		ContentBaseModelBase: *contentBaseModelBase,
		EID: id,
		UserEID: userEID,
		ParentID: parentID,
	}
}
