/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
  * Do not edit this file manually.
  * Automatically generated via `qing sod cmt/cmt`.
  * See `lib/dev/sod/objects/cmt/cmt.yaml` for details.
  ******************************************************************************************/

package cmt

import "qing/da"

type Cmt struct {
	da.CmtData

	EID         string  `json:"id"`
	UserURL     string  `json:"userURL"`
	UserEID     string  `json:"userID"`
	UserIconURL string  `json:"userIconURL"`
	CreatedAt   string  `json:"createdAt"`
	ModifiedAt  string  `json:"modifiedAt"`
	ParentID    *string `json:"parentID,omitempty"`
}

func NewCmt(cmtData *da.CmtData, id string, userURL string, userID string, userIconURL string, createdAt string, modifiedAt string, parentID *string) Cmt {
	return Cmt{
		CmtData: *cmtData,
		EID: id,
		UserURL: userURL,
		UserEID: userID,
		UserIconURL: userIconURL,
		CreatedAt: createdAt,
		ModifiedAt: modifiedAt,
		ParentID: parentID,
	}
}
