/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
  * Do not edit this file manually.
  * Automatically generated via `qing sod cmt/cmt`.
  * See `lib/dev/sod/objects/cmt/cmt.yaml` for details.
  ******************************************************************************************/

package cmt

import "qing/da"

type Cmt struct {
	da.CmtData

	EID         string `json:"id,omitempty"`
	UserURL     string `json:"userURL,omitempty"`
	UserEID     string `json:"userID,omitempty"`
	UserIconURL string `json:"userIconURL,omitempty"`
	CreatedAt   string `json:"createdAt,omitempty"`
	ModifiedAt  string `json:"modifiedAt,omitempty"`
}

func NewCmt(id string, userURL string, userID string, userIconURL string, createdAt string, modifiedAt string) Cmt {
	return Cmt{
		EID: id,
		UserURL: userURL,
		UserEID: userID,
		UserIconURL: userIconURL,
		CreatedAt: createdAt,
		ModifiedAt: modifiedAt,
	}
}
