/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
  * Do not edit this file manually.
  * Automatically generated via `qing sod cmt/cmt`.
  * See `lib/dev/sod/objects/cmt/cmt.yaml` for details.
  ******************************************************************************************/

package cmt

import (
  	"qing/da"
	"qing/r/rcom"
)

type Cmt struct {
	da.CmtData
	rcom.ContentBaseExtraProps

	EID      string  `json:"id"`
	UserURL  string  `json:"userURL"`
	ParentID *string `json:"parentID,omitempty"`
}

func NewCmt(cmtData *da.CmtData, contentBaseExtraProps *rcom.ContentBaseExtraProps, id string, userURL string, parentID *string) Cmt {
	return Cmt{
		CmtData: *cmtData,
		ContentBaseExtraProps: *contentBaseExtraProps,
		EID: id,
		UserURL: userURL,
		ParentID: parentID,
	}
}
