/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
* This code was automatically generated by `@qing/def`.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/

package appdef

const ForumStatusOpen = 0
const ForumStatusArchived = 1
const FormUploadMain = "main"
const DeleteFlagSelf = 1
const DeleteFlagHost = 2
const ApiLangParam = "__l"
const ErrGeneric = 1

type ContentBaseType int

const (
	ContentBaseTypePost ContentBaseType = iota + 1
	ContentBaseTypeCmt
	ContentBaseTypeThread
)

type HomePageFeedType int

const (
	HomePageFeedTypePost HomePageFeedType = iota + 1
	HomePageFeedTypeThread
)

type CommunityMode int

const (
	CommunityModeDisabled CommunityMode = iota + 1
	CommunityModeCommunity
	CommunityModeForums
)

type DelFlags int

const (
	DelFlagsSelf DelFlags = iota + 1
	DelFlagsHost
)

const (
	RouteM = "m"
	RouteMx = "mx"
	RouteApi = "s"
	RouteForum = "f"
	RouteForumGroup = "g"
	RouteThread = "t"
	RouteDev = "__"
	RouteAuth = "auth"
	RoutePost = "p"
	RouteUser = "u"
)

const (
	KeyPosts = "posts"
	KeyReplies = "replies"
	KeyPage = "page"
	KeyPageSize = "pageSize"
	KeyTab = "tab"
	KeyValue = "value"
	KeyThreads = "threads"
	KeyCommunitySettings = "communitySettings"
	KeyCreated = "createdAt"
	KeyLikes = "likes"
	KeyComments = "comments"
	KeyMessages = "messages"
	KeyLang = "lang"
	KeyCmt = "cmt"
)

const (
	LenMaxTitle = 200
	LenMaxEmail = 200
	LenMaxName = 100
	LenMaxFileName = 255
	LenMaxUserInfoField = 100
	LenMaxURL = 200
	LenMaxPwdHash = 255
	LenMinUserPwd = 6
	LenMaxUserPwd = 30
	LenMaxCaptcha = 10
	LenMaxLang = 10
	LenMaxGenericString = 100
)
