/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

/******************************************************************************************
 * Do not edit this file manually.
 * Automatically generated via `qing sod i`.
 * See `lib/dev/sod/objects/i.yaml` for details.
 ******************************************************************************************/

package iSod

import "qing/da"

type GetProfileInfo struct {
	da.DBUserForEditing

	IconURL string `json:"iconURL,omitempty"`
}

func NewGetProfileInfo(dBUserForEditing *da.DBUserForEditing, iconURL string) GetProfileInfo {
	return GetProfileInfo{
		DBUserForEditing: *dBUserForEditing,
		IconURL: iconURL,
	}
}
