/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

/******************************************************************************************
 * Do not edit this file manually.
 * Automatically generated via `qing sod feed`.
 * See `lib/dev/sod/objects/feed.yaml` for details.
 ******************************************************************************************/

package feedSod

type FeedBase struct {
	Link        string `json:"link,omitempty"`
	UserURL     string `json:"userURL,omitempty"`
	UserIconURL string `json:"userIconURL,omitempty"`
	CreatedAt   string `json:"createdAt,omitempty"`
	ModifiedAt  string `json:"modifiedAt,omitempty"`
}

func NewFeedBase(link string, userURL string, userIconURL string, createdAt string, modifiedAt string) FeedBase {
	return FeedBase{
		Link: link,
		UserURL: userURL,
		UserIconURL: userIconURL,
		CreatedAt: createdAt,
		ModifiedAt: modifiedAt,
	}
}
