/******************************************************************************************
* This code was automatically generated by go-const-gen.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/

package defs

// SharedConstants ...
type SharedConstants struct {
	ColumnComments string
	ColumnCreated string
	ColumnLikes string
	ColumnMessages string
	DefaultLang string
	EntityAnswer int
	EntityCmt int
	EntityDiscussion int
	EntityDiscussionMsg int
	EntityPost int
	EntityQuestion int
	EntityReply int
	ErrCaptchaNotFound int
	ErrCaptchaNotMatch int
	ErrGeneric int
	ErrInvalidUserOrPwd int
	ErrNeedAuth int
	KeyAnswers string
	KeyDiscussions string
	KeyPage string
	KeyPageSize string
	KeyPosts string
	KeyTab string
	MaxCaptchaLen int
	MaxGenericStringLen int
	MaxPostTitleLen int
	MaxUserEmailLen int
	MaxUserNameLen int
	MaxUserPwdLen int
	MinUserPwdLen int
	RouteApi string
	RouteAuth string
	RouteDashboard string
	RouteDiscussion string
	RouteForum string
	RoutePost string
	RouteTest string
	RouteUser string
}

// Constants ...
var Constants *SharedConstants

func init() {
	Constants = &SharedConstants{
		ColumnComments: "comments",
		ColumnCreated: "createdAt",
		ColumnLikes: "likes",
		ColumnMessages: "messages",
		DefaultLang: "en",
		EntityAnswer: 7,
		EntityCmt: 2,
		EntityDiscussion: 4,
		EntityDiscussionMsg: 6,
		EntityPost: 1,
		EntityQuestion: 5,
		EntityReply: 3,
		ErrCaptchaNotFound: 10002,
		ErrCaptchaNotMatch: 10003,
		ErrGeneric: 10000,
		ErrInvalidUserOrPwd: 1,
		ErrNeedAuth: 10001,
		KeyAnswers: "answers",
		KeyDiscussions: "discussions",
		KeyPage: "page",
		KeyPageSize: "pageSize",
		KeyPosts: "posts",
		KeyTab: "tab",
		MaxCaptchaLen: 10,
		MaxGenericStringLen: 100,
		MaxPostTitleLen: 200,
		MaxUserEmailLen: 200,
		MaxUserNameLen: 200,
		MaxUserPwdLen: 30,
		MinUserPwdLen: 6,
		RouteApi: "s",
		RouteAuth: "auth",
		RouteDashboard: "home",
		RouteDiscussion: "d",
		RouteForum: "f",
		RoutePost: "p",
		RouteTest: "test",
		RouteUser: "user",
	}
}
