/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
  * Do not edit this file manually.
  * Automatically generated via `qing sod qna/qnaWind`.
  * See `lib/dev/sod/objects/qna/qnaWind.yaml` for details.
  ******************************************************************************************/

package qnaWind

type QnaWind struct {
	QuestionID string `json:"questionID,omitempty"`
	ForumID    string `json:"forumID,omitempty"`
}

func NewQnaWind(questionID string, forumID string) QnaWind {
	return QnaWind{
		QuestionID: questionID,
		ForumID: forumID,
	}
}
