/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

/******************************************************************************************
 * Do not edit this file manually.
 * Automatically generated via `qing sod app`.
 * See `lib/dev/sod/objects/app.yaml` for details.
 ******************************************************************************************/

package appSod

type MainPageUserState struct {
	ID      string `json:"id,omitempty"`
	Name    string `json:"name,omitempty"`
	Url     string `json:"url,omitempty"`
	IconUrl string `json:"iconUrl,omitempty"`
	Admin   bool   `json:"admin,omitempty"`
}

func NewMainPageUserState(id string, name string, url string, iconUrl string, admin bool) MainPageUserState {
	return MainPageUserState{
		ID: id,
		Name: name,
		Url: url,
		IconUrl: iconUrl,
		Admin: admin,
	}
}

type MainPageStateData struct {
	User     *MainPageUserState `json:"user,omitempty"`
	PostPerm int                `json:"postPerm,omitempty"`
	Forums   bool               `json:"forums,omitempty"`
}

func NewMainPageStateData(user *MainPageUserState, postPerm int, forums bool) MainPageStateData {
	return MainPageStateData{
		User: user,
		PostPerm: postPerm,
		Forums: forums,
	}
}
