/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

/******************************************************************************************
 * Do not edit this file manually.
 * Automatically generated via `qing sod app`.
 * See `lib/dev/sod/objects/app.yaml` for details.
 ******************************************************************************************/

package appSod

type RawMainPageWind struct {
	AppUserID         string `json:"appUserID,omitempty"`
	AppUserName       string `json:"appUserName,omitempty"`
	AppUserURL        string `json:"appUserURL,omitempty"`
	AppUserIconURL    string `json:"appUserIconURL,omitempty"`
	AppUserAdmin      bool   `json:"appUserAdmin,omitempty"`
	AppLang           string `json:"appLang,omitempty"`
	AppPostPerm       int    `json:"appPostPerm,omitempty"`
	AppForums         bool   `json:"appForums,omitempty"`
	AppWindDataString string `json:"appWindDataString,omitempty"`
}

func NewRawMainPageWind(appUserID string, appUserName string, appUserURL string, appUserIconURL string, appUserAdmin bool, appLang string, appPostPerm int, appForums bool, appWindDataString string) RawMainPageWind {
	return RawMainPageWind{
		AppUserID: appUserID,
		AppUserName: appUserName,
		AppUserURL: appUserURL,
		AppUserIconURL: appUserIconURL,
		AppUserAdmin: appUserAdmin,
		AppLang: appLang,
		AppPostPerm: appPostPerm,
		AppForums: appForums,
		AppWindDataString: appWindDataString,
	}
}
