CREATE TABLE `answer` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`content` TEXT NOT NULL,
	`user_id` BIGINT UNSIGNED NOT NULL,
	`created_at` DATETIME NOT NULL,
	`modified_at` DATETIME NULL DEFAULT NULL,
	`cmt_count` INT UNSIGNED NOT NULL DEFAULT 0,
	`question_id` BIGINT UNSIGNED NOT NULL,
	`votes` INT UNSIGNED NOT NULL DEFAULT 0,
	`up_votes` INT UNSIGNED NOT NULL DEFAULT 0,
	`down_votes` INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	CONSTRAINT FOREIGN KEY(`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY(`question_id`) REFERENCES `question` (`id`) ON DELETE CASCADE
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
