CREATE TABLE `forum` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`display_name` VARCHAR(200) NOT NULL,
	`created_at` DATETIME NOT NULL,
	`desc` TEXT NULL DEFAULT NULL,
	`group_id` BIGINT UNSIGNED NOT NULL,
	`post_count` INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	CONSTRAINT FOREIGN KEY(`group_id`) REFERENCES `forum_group` (`id`) ON DELETE CASCADE
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
