/******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

CREATE TABLE `forum_group` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`desc` TEXT NOT NULL,
	`created_at` DATETIME NOT NULL,
	`desc_modified_at` DATETIME NULL DEFAULT NULL,
	`child_count` INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`)
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
