CREATE TABLE `forum_post` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`content` TEXT NOT NULL,
	`user_id` BIGINT UNSIGNED NOT NULL,
	`created_at` DATETIME NOT NULL,
	`modified_at` DATETIME NULL DEFAULT NULL,
	`cmt_count` INT UNSIGNED NOT NULL,
	`title` VARCHAR(255) NOT NULL,
	`forum_id` BIGINT UNSIGNED NOT NULL,
	`votes` INT UNSIGNED NOT NULL,
	`up_votes` INT UNSIGNED NOT NULL,
	`down_votes` INT UNSIGNED NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT FOREIGN KEY(`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY(`forum_id`) REFERENCES `forum` (`id`) ON DELETE CASCADE
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
