CREATE TABLE `forum_group` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`display_name` VARCHAR(200) NOT NULL,
	`created_at` DATETIME NOT NULL,
	`desc` TEXT NULL DEFAULT NULL,
	`forum_count` INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`)
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
