CREATE TABLE `post_cmt` (
	`host_id` BIGINT UNSIGNED NOT NULL,
	`cmt_id` BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (`host_id`, `cmt_id`),
	CONSTRAINT FOREIGN KEY(`host_id`) REFERENCES `post` (`id`) ON DELETE CASCADE,
	CONSTRAINT FOREIGN KEY(`cmt_id`) REFERENCES `cmt` (`id`) ON DELETE CASCADE
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
