/******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

CREATE TABLE `user` (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(255) NOT NULL UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`icon_name` VARCHAR(255) NOT NULL DEFAULT '',
	`created_time` DATETIME NOT NULL,
	`company` VARCHAR(100) NOT NULL DEFAULT '',
	`website` VARCHAR(100) NOT NULL DEFAULT '',
	`location` VARCHAR(100) NOT NULL DEFAULT '',
	`bio` TEXT NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
