CREATE TABLE `user_stats` (
	`id` BIGINT UNSIGNED NOT NULL,
	`post_count` INT UNSIGNED NOT NULL DEFAULT 0,
	`form_post_count` INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`)
)
CHARACTER SET=utf8mb4
COLLATE=utf8mb4_unicode_ci
;
