/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
  * Do not edit this file manually.
  * Automatically generated via `qing sod dev/auth/tUserInfo`.
  * See `lib/dev/sod/objects/dev/auth/tUserInfo.yaml` for details.
  ******************************************************************************************/

export interface TUserInfo {
  id: string;
  name?: string;
  iconName?: string;
  admin?: boolean;
}
