/*
 * Copyright (C) 2021 The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that can
 * be found in the LICENSE file.
 */

import np from 'path';
import confgen from 'jsconfgen';
import { serverPath, copyrightStringYAML } from '../common/common.js';

const header = `${copyrightStringYAML}# This file was automatically generated by running \`qing d conf\`
# Do not edit this file manually, your changes will be overwritten.

`;

async function buildConf() {
  const serverDir = serverPath();
  const src = np.join(serverDir, 'docker-compose.mjs');
  const dest = np.join(serverDir, 'docker-compose.yml');
  await confgen('yaml', src, dest, { header });
}

await buildConf();
