/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
  * Do not edit this file manually.
  * Automatically generated via `qing sod post/postWind`.
  * See `lib/dev/sod/objects/post/postWind.yaml` for details.
  ******************************************************************************************/

package postWind

type PostWind struct {
	ID              string `json:"id"`
	CmtCount        uint   `json:"cmtCount"`
	InitialLikes    uint   `json:"initialLikes"`
	InitialHasLiked bool   `json:"initialHasLiked,omitempty"`
}

func NewPostWind(id string, cmtCount uint, initialLikes uint, initialHasLiked bool) PostWind {
	return PostWind{
		ID: id,
		CmtCount: cmtCount,
		InitialLikes: initialLikes,
		InitialHasLiked: initialHasLiked,
	}
}
