/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
 * Do not edit this file manually.
 * Automatically generated via `qing sod app/rawMainPageWind`.
 * See `lib/dev/sod/objects/app/rawMainPageWind.yaml` for details.
 ******************************************************************************************/

package appSod

type RawMainPageWind struct {
	AppUserID         string `json:"appUserID,omitempty"`
	AppUserName       string `json:"appUserName,omitempty"`
	AppUserURL        string `json:"appUserURL,omitempty"`
	AppUserIconURL    string `json:"appUserIconURL,omitempty"`
	AppUserAdmin      bool   `json:"appUserAdmin,omitempty"`
	AppLang           string `json:"appLang,omitempty"`
	AppCommunityMode  int    `json:"appCommunityMode,omitempty"`
	AppWindDataString string `json:"appWindDataString,omitempty"`
}
