version: '3.9'

services:
  server:
    build: .
    volumes:
      - .:/server
      - ../web:/web
      - ../userland:/userland
      - ../app_data:/app_data
      - &volume_app_tmp '../app_tmp:/app_tmp'
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - db
      - img_proxy
  redis:
    image: 'redis:6'
    ports:
      - '6379:6379'
  db:
    image: 'mariadb:10.6'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: qing_dev_root_pwd
      MYSQL_USER: qing_dev
      MYSQL_PASSWORD: qing_dev_pwd
      MYSQL_DATABASE: qing_dev_db
  migrate:
    image: 'migrate/migrate'
    profiles: ['oth']
    volumes:
      - ../migrations:/migrations
    entrypoint:
      [
        'migrate',
        '-path',
        '/migrations',
        '-database',
        'mysql://qing_dev:qing_dev_pwd@tcp(db:3306)/qing_dev_db?multiStatements=true',
      ]
    depends_on:
      - db
  img_proxy:
    image: 'h2non/imaginary'
    ports:
      - '9000:9000'
    volumes:
      - *volume_app_tmp
