/** DO NOT EDIT. This file was automatically generated by `/tools/build-shared-const.ts`. */

package app

// SharedConstants ...
type SharedConstants struct {
	MaxPostTitleLen int `json:"maxPostTitleLen"`
	MaxUserEmailLen int `json:"maxUserEmailLen"`
	MaxUserNameLen  int `json:"maxUserNameLen"`
	MaxUserPwdLen   int `json:"maxUserPwdLen"`
	MinUserPwdLen   int `json:"minUserPwdLen"`
}

// Constants ...
var Constants *SharedConstants

func init() {
	Constants = &SharedConstants{
		MaxPostTitleLen: 200,
		MaxUserEmailLen: 200,
		MaxUserNameLen:  200,
		MaxUserPwdLen:   30,
		MinUserPwdLen:   6,
	}
}
