/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
* This code was automatically generated by `@qing/def`.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/package dbdef


type ThreadType int

const (
	ThreadTypeQue ThreadType = iota + 1
	ThreadTypeDis
)

type CmtHostType int

const (
	CmtHostTypePost CmtHostType = iota + 1
	CmtHostTypeQue
	CmtHostTypeDis
	CmtHostTypeAns
)

type LikeHostType int

const (
	LikeHostTypePost LikeHostType = iota + 1
	LikeHostTypeQue
	LikeHostTypeCmt
)
