/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

export interface CmtResult {
  cmtCount?: number;
  contentHTML?: string;
  isLiked?: number;
  likes?: number;
  userName?: string;
}

export interface EntityGetSrcResult {
  contentHTML?: string;
  title?: string;
}
