/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
* This code was automatically generated by `@qing/def`.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/

package infdef

const QingDir = "/qing"
const QingDataDir = "/qing_data"
const DevCSSDir = "/qing/dev/css"
const DevConfigDir = "/qing/dev/config"
const DevServerDir = "/qing/dev/server"
const MiscDir = "/qing/misc"
const ConfigSchemaFile = "/qing/misc/config_schema.json"
const TemplateDir = "/qing/templates"
const StaticDir = "/qing/static"
const LangsDir = "/qing/langs"
const MigrationsDir = "/qing/migrations"
const ConfigFile = "/qing/config.json"
const ProfileFile = "/qing/profile.json"
const DevConfEnv = "QING_DCONF"
