package captchax

import (
	"bytes"
	"fmt"
	"io"
	"qing/app/defs"
	"qing/app/errs"
	"qing/app/extern/redisx"
	"strconv"

	"github.com/mgenware/go-captcha"
)

const ResultVerified = 1
const ResultNotVerified = -1

type CaptchaService struct {
	redisConn *redisx.Conn
}

var allowedTypes map[int]bool

func init() {
	allowedTypes = make(map[int]bool)
	allowedTypes[defs.EntityPost] = true
	allowedTypes[defs.EntityCmt] = true
	allowedTypes[defs.EntityReply] = true
}

// NewCaptchaService creates a CaptchaService.
func NewCaptchaService(redisConn *redisx.Conn) *CaptchaService {
	return &CaptchaService{redisConn: redisConn}
}

// IsTypeAllowed determines if the specified etype is allowed in this service.
func (c *CaptchaService) IsTypeAllowed(etype int) bool {
	return allowedTypes[etype]
}

// WriteCaptcha flushes a captcha image generated by the given parameters to the specified io.Writer.
func (c *CaptchaService) WriteCaptcha(uid uint64, etype int, length int, w io.Writer) error {
	code := captcha.RandomDigits(length)
	codeStr := c.bytesToString(code)
	err := c.registerCaptcha(uid, etype, codeStr)
	if err != nil {
		return err
	}
	img := captcha.NewImage("", code, 150, 45)
	_, err = img.WriteTo(w)
	if err != nil {
		return err
	}
	return nil
}

// Verify checks if the specified code matches the internal code stored in memory.
func (c *CaptchaService) Verify(uid uint64, etype int, code string) (int, error) {
	key := c.getMSKey(uid, etype)
	result, err := c.redisConn.GetStringValue(key)
	if err != nil {
		return 0, err
	}
	if result == "" {
		return errs.CaptchaNotFound, nil
	}
	if result != code {
		return errs.CaptchaNotMatch, nil
	}
	return 0, nil
}

func (c *CaptchaService) getMSKey(uid uint64, etype int) string {
	return fmt.Sprintf(defs.MSCaptcha, uid, etype)
}

func (c *CaptchaService) registerCaptcha(uid uint64, category int, value string) error {
	key := c.getMSKey(uid, category)
	return c.redisConn.SetStringValue(key, value, defs.MSCaptchaTimeout)
}

// Converts bytes from `captcha.RandomDigits` to a string.
func (c *CaptchaService) bytesToString(digits []byte) string {
	var buffer bytes.Buffer
	for _, d := range digits {
		buffer.WriteString(strconv.Itoa(int(d)))
	}
	return buffer.String()
}
