/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

/******************************************************************************************
 * Do not edit this file manually.
 * Automatically generated via `qing sod dev/auth`.
 * See `lib/dev/sod/objects/dev/auth.yaml` for details.
 ******************************************************************************************/

package authSod

type TUserInfo struct {
	Admin   bool   `json:"admin,omitempty"`
	ID      string `json:"id,omitempty"`
	IconURL string `json:"iconURL,omitempty"`
	Link    string `json:"link,omitempty"`
	Name    string `json:"name,omitempty"`
}

func NewTUserInfo(admin bool, id string, iconURL string, link string, name string) TUserInfo {
	return TUserInfo{
		Admin: admin,
		ID: id,
		IconURL: iconURL,
		Link: link,
		Name: name,
	}
}
