/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import (
	"database/sql"
	"fmt"
	"time"

	"github.com/mgenware/mingru-go-lib"
)

type TableTypeAnswer struct {
}

var Answer = &TableTypeAnswer{}

// MingruSQLName returns the name of this table.
func (mrTable *TableTypeAnswer) MingruSQLName() string {
	return "answer"
}

// ------------ Actions ------------

func (mrTable *TableTypeAnswer) deleteItemChild1(mrQueryable mingru.Queryable, id uint64) (uint64, error) {
	var result uint64
	err := mrQueryable.QueryRow("SELECT `question_id` FROM `answer` WHERE `id` = ?", id).Scan(&result)
	if err != nil {
		return result, err
	}
	return result, nil
}

func (mrTable *TableTypeAnswer) deleteItemChild2(mrQueryable mingru.Queryable, id uint64, userID uint64) error {
	result, err := mrQueryable.Exec("DELETE FROM `answer` WHERE (`id` = ? AND `user_id` = ?)", id, userID)
	return mingru.CheckOneRowAffectedWithError(result, err)
}

func (mrTable *TableTypeAnswer) deleteItemChild3(mrQueryable mingru.Queryable, id uint64) error {
	return ThreadBaseUtil.UpdateReplyCount(mrQueryable, Answer, -1, id)
}

func (mrTable *TableTypeAnswer) DeleteItem(db *sql.DB, id uint64, userID uint64) error {
	txErr := mingru.Transact(db, func(tx *sql.Tx) error {
		var err error
		questionID, err := mrTable.deleteItemChild1(tx, id)
		if err != nil {
			return err
		}
		err = mrTable.deleteItemChild2(tx, id, userID)
		if err != nil {
			return err
		}
		err = mrTable.deleteItemChild3(tx, questionID)
		if err != nil {
			return err
		}
		return nil
	})
	return txErr
}

func (mrTable *TableTypeAnswer) EditItem(mrQueryable mingru.Queryable, contentHTML string, rawModifiedAt time.Time, id uint64, userID uint64, sanitizedStub int) error {
	result, err := mrQueryable.Exec("UPDATE `answer` SET `content` = ?, `modified_at` = ? WHERE (`id` = ? AND `user_id` = ?)", contentHTML, rawModifiedAt, id, userID)
	return mingru.CheckOneRowAffectedWithError(result, err)
}

func (mrTable *TableTypeAnswer) insertItemChild1(mrQueryable mingru.Queryable, contentHTML string, userID uint64, rawCreatedAt time.Time, rawModifiedAt time.Time, questionID uint64) (uint64, error) {
	result, err := mrQueryable.Exec("INSERT INTO `answer` (`content`, `user_id`, `created_at`, `modified_at`, `question_id`, `cmt_count`, `votes`, `up_votes`, `down_votes`) VALUES (?, ?, ?, ?, ?, 0, 0, 0, 0)", contentHTML, userID, rawCreatedAt, rawModifiedAt, questionID)
	return mingru.GetLastInsertIDUint64WithError(result, err)
}

func (mrTable *TableTypeAnswer) insertItemChild2(mrQueryable mingru.Queryable, id uint64) error {
	return ThreadBaseUtil.UpdateReplyCount(mrQueryable, Answer, 1, id)
}

func (mrTable *TableTypeAnswer) InsertItem(db *sql.DB, contentHTML string, userID uint64, rawCreatedAt time.Time, rawModifiedAt time.Time, questionID uint64, sanitizedStub int, captStub int) (uint64, error) {
	var insertedIDExported uint64
	txErr := mingru.Transact(db, func(tx *sql.Tx) error {
		var err error
		insertedID, err := mrTable.insertItemChild1(tx, contentHTML, userID, rawCreatedAt, rawModifiedAt, questionID)
		if err != nil {
			return err
		}
		err = mrTable.insertItemChild2(tx, questionID)
		if err != nil {
			return err
		}
		insertedIDExported = insertedID
		return nil
	})
	return insertedIDExported, txErr
}

type AnswerTableSelectItemsByQuestionResult struct {
	CmtCount      uint      `json:"cmtCount,omitempty"`
	ContentHTML   string    `json:"contentHTML,omitempty"`
	DownVotes     uint      `json:"downVotes,omitempty"`
	ID            uint64    `json:"-"`
	RawCreatedAt  time.Time `json:"-"`
	RawModifiedAt time.Time `json:"-"`
	UpVotes       uint      `json:"upVotes,omitempty"`
	UserIconName  string    `json:"-"`
	UserID        uint64    `json:"-"`
	UserName      string    `json:"-"`
	Votes         int       `json:"votes,omitempty"`
}

func (mrTable *TableTypeAnswer) SelectItemsByQuestion(mrQueryable mingru.Queryable, questionID uint64, page int, pageSize int) ([]AnswerTableSelectItemsByQuestionResult, bool, error) {
	if page <= 0 {
		err := fmt.Errorf("Invalid page %v", page)
		return nil, false, err
	}
	if pageSize <= 0 {
		err := fmt.Errorf("Invalid page size %v", pageSize)
		return nil, false, err
	}
	limit := pageSize + 1
	offset := (page - 1) * pageSize
	max := pageSize
	rows, err := mrQueryable.Query("SELECT `answer`.`id`, `answer`.`user_id`, `join_1`.`name`, `join_1`.`icon_name`, `answer`.`created_at`, `answer`.`modified_at`, `answer`.`content`, `answer`.`cmt_count`, `answer`.`up_votes`, `answer`.`down_votes`, `answer`.`votes` FROM `answer` AS `answer` INNER JOIN `user` AS `join_1` ON `join_1`.`id` = `answer`.`user_id` WHERE `answer`.`question_id` = ? ORDER BY `answer`.`created_at` LIMIT ? OFFSET ?", questionID, limit, offset)
	if err != nil {
		return nil, false, err
	}
	result := make([]AnswerTableSelectItemsByQuestionResult, 0, limit)
	itemCounter := 0
	defer rows.Close()
	for rows.Next() {
		itemCounter++
		if itemCounter <= max {
			var item AnswerTableSelectItemsByQuestionResult
			err = rows.Scan(&item.ID, &item.UserID, &item.UserName, &item.UserIconName, &item.RawCreatedAt, &item.RawModifiedAt, &item.ContentHTML, &item.CmtCount, &item.UpVotes, &item.DownVotes, &item.Votes)
			if err != nil {
				return nil, false, err
			}
			result = append(result, item)
		}
	}
	err = rows.Err()
	if err != nil {
		return nil, false, err
	}
	return result, itemCounter > len(result), nil
}

func (mrTable *TableTypeAnswer) SelectItemSrc(mrQueryable mingru.Queryable, id uint64, userID uint64) (EntityGetSrcResult, error) {
	var result EntityGetSrcResult
	err := mrQueryable.QueryRow("SELECT `content` FROM `answer` WHERE (`id` = ? AND `user_id` = ?)", id, userID).Scan(&result.ContentHTML)
	if err != nil {
		return result, err
	}
	return result, nil
}

func (mrTable *TableTypeAnswer) TestUpdateDates(mrQueryable mingru.Queryable, rawCreatedAt time.Time, rawModifiedAt time.Time, id uint64) error {
	result, err := mrQueryable.Exec("UPDATE `answer` SET `created_at` = ?, `modified_at` = ? WHERE `id` = ?", rawCreatedAt, rawModifiedAt, id)
	return mingru.CheckOneRowAffectedWithError(result, err)
}
