/******************************************************************************************
* This code was automatically generated by go-const-gen.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/

package da

// SharedConstants ...
type SharedConstants struct {
	ThreadTypeDiscussion int
	ThreadTypePost int
	ThreadTypeQuestion int
}

// Constants ...
var Constants *SharedConstants

func init() {
	Constants = &SharedConstants{
		ThreadTypeDiscussion: 3,
		ThreadTypePost: 1,
		ThreadTypeQuestion: 2,
	}
}
