/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import "github.com/mgenware/mingru-go-lib"

type ContentBaseStaticAGType struct {
}

var ContentBaseStatic = &ContentBaseStaticAGType{}

// ------------ Actions ------------

func (mrTable *ContentBaseStaticAGType) UpdateCmtCount(mrQueryable mingru.Queryable, contentBaseTableParam mingru.Table, id uint64, offset int) error {
	result, err := mrQueryable.Exec("UPDATE "+string(contentBaseTableParam)+" SET `cmt_count` = `cmt_count` + ? WHERE `id` = ?", offset, id)
	return mingru.CheckOneRowAffectedWithError(result, err)
}
