/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

/******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import "github.com/mgenware/mingru-go-lib"

type ContentBaseStaticAGType struct {
}

var ContentBaseStatic = &ContentBaseStaticAGType{}

// ------------ Actions ------------

func (mrTable *ContentBaseStaticAGType) SelectUserID(mrQueryable mingru.Queryable, contentBaseTableParam mingru.Table, id uint64) (uint64, error) {
	var result uint64
	err := mrQueryable.QueryRow("SELECT `user_id` FROM "+string(contentBaseTableParam)+" WHERE `id` = ?", id).Scan(&result)
	if err != nil {
		return result, err
	}
	return result, nil
}

func (mrTable *ContentBaseStaticAGType) UpdateCmtCount(mrQueryable mingru.Queryable, contentBaseTableParam mingru.Table, id uint64, offset int) error {
	result, err := mrQueryable.Exec("UPDATE "+string(contentBaseTableParam)+" SET `cmt_count` = `cmt_count` + ? WHERE `id` = ?", offset, id)
	return mingru.CheckOneRowAffectedWithError(result, err)
}
