/******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import "github.com/mgenware/mingru-go-lib"

// TableTypeForumIsUserMod ...
type TableTypeForumIsUserMod struct {
}

// ForumIsUserMod ...
var ForumIsUserMod = &TableTypeForumIsUserMod{}

// ------------ Actions ------------

// Get ...
func (da *TableTypeForumIsUserMod) Get(queryable mingru.Queryable, id uint64) (bool, error) {
	var result bool
	err := queryable.QueryRow("SELECT EXISTS(SELECT * FROM `forum_is_user_mod` WHERE `id` = ?)", id).Scan(&result)
	if err != nil {
		return result, err
	}
	return result, nil
}
