/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import (
	"fmt"
	"time"

	"github.com/mgenware/mingru-go-lib"
)

type TableTypeForum struct {
}

var Forum = &TableTypeForum{}

// MingruSQLName returns the name of this table.
func (mrTable *TableTypeForum) MingruSQLName() string {
	return "forum"
}

// ------------ Actions ------------

func (mrTable *TableTypeForum) DeleteItem(mrQueryable mingru.Queryable, id uint64) error {
	result, err := mrQueryable.Exec("DELETE FROM `forum` WHERE `id` = ?", id)
	return mingru.CheckOneRowAffectedWithError(result, err)
}

func (mrTable *TableTypeForum) InsertItem(mrQueryable mingru.Queryable, name string, descHTML string, orderIndex uint, rawCreatedAt time.Time, groupID *uint64, threadCount uint, status uint8) (uint64, error) {
	result, err := mrQueryable.Exec("INSERT INTO `forum` (`name`, `desc`, `order_index`, `created_at`, `group_id`, `thread_count`, `status`) VALUES (?, ?, ?, ?, ?, ?, ?)", name, descHTML, orderIndex, rawCreatedAt, groupID, threadCount, status)
	return mingru.GetLastInsertIDUint64WithError(result, err)
}

type ForumTableSelectForumResult struct {
	DescHTML     string    `json:"descHTML,omitempty"`
	ID           uint64    `json:"id,omitempty"`
	Name         string    `json:"name,omitempty"`
	RawCreatedAt time.Time `json:"-"`
	ThreadCount  uint      `json:"threadCount,omitempty"`
}

func (mrTable *TableTypeForum) SelectForum(mrQueryable mingru.Queryable, id uint64) (ForumTableSelectForumResult, error) {
	var result ForumTableSelectForumResult
	err := mrQueryable.QueryRow("SELECT `id`, `name`, `desc`, `created_at`, `thread_count` FROM `forum` WHERE `id` = ?", id).Scan(&result.ID, &result.Name, &result.DescHTML, &result.RawCreatedAt, &result.ThreadCount)
	if err != nil {
		return result, err
	}
	return result, nil
}

func (mrTable *TableTypeForum) SelectForumIDsForGroup(mrQueryable mingru.Queryable, groupID uint64) ([]uint64, error) {
	rows, err := mrQueryable.Query("SELECT `id` FROM `forum` WHERE `group_id` = ?", groupID)
	if err != nil {
		return nil, err
	}
	var result []uint64
	defer rows.Close()
	for rows.Next() {
		var item uint64
		err = rows.Scan(&item)
		if err != nil {
			return nil, err
		}
		result = append(result, item)
	}
	err = rows.Err()
	if err != nil {
		return nil, err
	}
	return result, nil
}

func (mrTable *TableTypeForum) SelectGroupID(mrQueryable mingru.Queryable, id uint64) (*uint64, error) {
	var result *uint64
	err := mrQueryable.QueryRow("SELECT `group_id` FROM `forum` WHERE `id` = ?", id).Scan(&result)
	if err != nil {
		return result, err
	}
	return result, nil
}

type ForumTableSelectInfoForEditingResult struct {
	DescHTML string `json:"descHTML,omitempty"`
	Name     string `json:"name,omitempty"`
}

func (mrTable *TableTypeForum) SelectInfoForEditing(mrQueryable mingru.Queryable, id uint64) (ForumTableSelectInfoForEditingResult, error) {
	var result ForumTableSelectInfoForEditingResult
	err := mrQueryable.QueryRow("SELECT `name`, `desc` FROM `forum` WHERE `id` = ?", id).Scan(&result.Name, &result.DescHTML)
	if err != nil {
		return result, err
	}
	return result, nil
}

func (mrTable *TableTypeForum) SelectThreads(mrQueryable mingru.Queryable, forumID *uint64, page int, pageSize int) ([]UserThreadInterface, bool, error) {
	if page <= 0 {
		err := fmt.Errorf("Invalid page %v", page)
		return nil, false, err
	}
	if pageSize <= 0 {
		err := fmt.Errorf("Invalid page size %v", pageSize)
		return nil, false, err
	}
	limit := pageSize + 1
	offset := (page - 1) * pageSize
	max := pageSize
	rows, err := mrQueryable.Query("SELECT `thread`.`id`, `thread`.`user_id`, `join_1`.`name`, `join_1`.`icon_name`, `thread`.`created_at`, `thread`.`modified_at`, `thread`.`title`, `thread`.`msg_count` AS `value1`, 0 AS `value2`, 0 AS `value3`, `thread`.`last_replied_at` FROM `thread` AS `thread` INNER JOIN `user` AS `join_1` ON `join_1`.`id` = `thread`.`user_id` WHERE `thread`.`forum_id` = ? ORDER BY `thread`.`last_replied_at` LIMIT ? OFFSET ?", forumID, limit, offset)
	if err != nil {
		return nil, false, err
	}
	result := make([]UserThreadInterface, 0, limit)
	itemCounter := 0
	defer rows.Close()
	for rows.Next() {
		itemCounter++
		if itemCounter <= max {
			var item UserThreadInterface
			err = rows.Scan(&item.ID, &item.UserID, &item.UserName, &item.UserIconName, &item.RawCreatedAt, &item.RawModifiedAt, &item.Title, &item.Value1, &item.Value2, &item.Value3, &item.LastRepliedAt)
			if err != nil {
				return nil, false, err
			}
			result = append(result, item)
		}
	}
	err = rows.Err()
	if err != nil {
		return nil, false, err
	}
	return result, itemCounter > len(result), nil
}

func (mrTable *TableTypeForum) UpdateInfo(mrQueryable mingru.Queryable, id uint64, name string, descHTML string) error {
	result, err := mrQueryable.Exec("UPDATE `forum` SET `name` = ?, `desc` = ? WHERE `id` = ?", name, descHTML, id)
	return mingru.CheckOneRowAffectedWithError(result, err)
}
