/******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import (
	"time"

	"github.com/mgenware/mingru-go-lib"
)

// TableTypeForumGroup ...
type TableTypeForumGroup struct {
}

// ForumGroup ...
var ForumGroup = &TableTypeForumGroup{}

// ------------ Actions ------------

// DeleteGroup ...
func (da *TableTypeForumGroup) DeleteGroup(queryable mingru.Queryable, id uint64) error {
	result, err := queryable.Exec("DELETE FROM `forum_group` WHERE `id` = ?", id)
	return mingru.CheckOneRowAffectedWithError(result, err)
}

// ForumGroupTableSelectGroupResult ...
type ForumGroupTableSelectGroupResult struct {
	ID             uint64     `json:"ID,omitempty"`
	Name           string     `json:"name,omitempty"`
	DescHTML       string     `json:"descHTML,omitempty"`
	CreatedAt      time.Time  `json:"createdAt,omitempty"`
	DescModifiedAt *time.Time `json:"descModifiedAt,omitempty"`
	ChildCount     uint       `json:"childCount,omitempty"`
}

// SelectGroup ...
func (da *TableTypeForumGroup) SelectGroup(queryable mingru.Queryable, id uint64) (*ForumGroupTableSelectGroupResult, error) {
	result := &ForumGroupTableSelectGroupResult{}
	err := queryable.QueryRow("SELECT `id`, `name`, `desc`, `created_at`, `desc_modified_at`, `child_count` FROM `forum_group` WHERE `id` = ?", id).Scan(&result.ID, &result.Name, &result.DescHTML, &result.CreatedAt, &result.DescModifiedAt, &result.ChildCount)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// UpdateDesc ...
func (da *TableTypeForumGroup) UpdateDesc(queryable mingru.Queryable, id uint64, desc string) error {
	result, err := queryable.Exec("UPDATE `forum_group` SET `desc` = ?, `desc_modified_at` = UTC_TIMESTAMP() WHERE `id` = ?", desc, id)
	return mingru.CheckOneRowAffectedWithError(result, err)
}

// UpdateName ...
func (da *TableTypeForumGroup) UpdateName(queryable mingru.Queryable, id uint64, name string) error {
	result, err := queryable.Exec("UPDATE `forum_group` SET `name` = ? WHERE `id` = ?", name, id)
	return mingru.CheckOneRowAffectedWithError(result, err)
}
