/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import "github.com/mgenware/mingru-go-lib"

type PostStaticAGType struct {
}

var PostStatic = &PostStaticAGType{}

// ------------ Actions ------------

func (mrTable *PostStaticAGType) UpdateLastRepliedAt(mrQueryable mingru.Queryable, postTableParam mingru.Table, id uint64) error {
	result, err := mrQueryable.Exec("UPDATE "+string(postTableParam)+" SET `last_replied_at` = NOW() WHERE `id` = ?", id)
	return mingru.CheckOneRowAffectedWithError(result, err)
}
