 /******************************************************************************************
 * This code was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import (
	"github.com/mgenware/go-packagex/v5/dbx"
)

// TableTypeReply ...
type TableTypeReply struct {
}

// Reply ...
var Reply = &TableTypeReply{}

// ------------ Actions ------------

// DeleteCmt ...
func (da *TableTypeReply) DeleteCmt(queryable dbx.Queryable, id uint64, userID uint64) error {
	result, err := queryable.Exec("DELETE FROM `reply` WHERE `id` = ? AND `user_id` = ?", id, userID)
	return dbx.CheckOneRowAffectedWithError(result, err)
}

// EditCmt ...
func (da *TableTypeReply) EditCmt(queryable dbx.Queryable, id uint64, userID uint64, content string, sanitizedStub int) error {
	result, err := queryable.Exec("UPDATE `reply` SET `content` = ? WHERE `id` = ? AND `user_id` = ?", content, id, userID)
	return dbx.CheckOneRowAffectedWithError(result, err)
}

// ReplyTableSelectCmtSourceResult ...
type ReplyTableSelectCmtSourceResult struct {
	Content string `json:"content,omitempty"`
}

// SelectCmtSource ...
func (da *TableTypeReply) SelectCmtSource(queryable dbx.Queryable, id uint64, userID uint64) (*ReplyTableSelectCmtSourceResult, error) {
	result := &ReplyTableSelectCmtSourceResult{}
	err := queryable.QueryRow("SELECT `content` FROM `reply` WHERE `id` = ? AND `user_id` = ?", id, userID).Scan(&result.Content)
	if err != nil {
		return nil, err
	}
	return result, nil
}
