/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

const TableUser = "user"
const TableUserStats = "user_stats"
const TableUserAuth = "user_auth"
const TableUserPwd = "user_pwd"
const TableForumGroup = "forum_group"
const TableForum = "forum"
const TableForumMod = "forum_mod"
const TableForumGroupMod = "forum_group_mod"
const TableForumIsUserMod = "forum_is_user_mod"
const TableCmt = "cmt"
const TablePost = "post"
const TablePostCmt = "post_cmt"
const TableThread = "thread"
const TableThreadCmt = "thread_cmt"
const TableThreadMsg = "thread_msg"
const TableThreadMsgCmt = "thread_msg_cmt"
const TablePostLike = "post_like"
const TableCmtLike = "cmt_like"
const TableThreadLike = "thread_like"
const TableThreadMsgLike = "thread_msg_like"
