/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

type TableTypePostCmt struct {
}

var PostCmt = &TableTypePostCmt{}

// MingruSQLName returns the name of this table.
func (mrTable *TableTypePostCmt) MingruSQLName() string {
	return "post_cmt"
}

type TableTypeDiscussionCmt struct {
}

var DiscussionCmt = &TableTypeDiscussionCmt{}

// MingruSQLName returns the name of this table.
func (mrTable *TableTypeDiscussionCmt) MingruSQLName() string {
	return "discussion_cmt"
}

type TableTypeDiscussionMsgCmt struct {
}

var DiscussionMsgCmt = &TableTypeDiscussionMsgCmt{}

// MingruSQLName returns the name of this table.
func (mrTable *TableTypeDiscussionMsgCmt) MingruSQLName() string {
	return "discussion_msg_cmt"
}

type TableTypeQuestionCmt struct {
}

var QuestionCmt = &TableTypeQuestionCmt{}

// MingruSQLName returns the name of this table.
func (mrTable *TableTypeQuestionCmt) MingruSQLName() string {
	return "question_cmt"
}

type TableTypeAnswerCmt struct {
}

var AnswerCmt = &TableTypeAnswerCmt{}

// MingruSQLName returns the name of this table.
func (mrTable *TableTypeAnswerCmt) MingruSQLName() string {
	return "answer_cmt"
}
