/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import (
	"database/sql"
	"fmt"
	"time"

	"github.com/mgenware/mingru-go-lib"
)

type ThreadAGType struct {
}

var Thread = &ThreadAGType{}

// ------------ Actions ------------

func (mrTable *ThreadAGType) deleteItemChild1(mrQueryable mingru.Queryable, id uint64, userID uint64) error {
	result, err := mrQueryable.Exec("DELETE FROM `thread` WHERE (`id` = ? AND `user_id` = ?)", id, userID)
	return mingru.CheckOneRowAffectedWithError(result, err)
}

func (mrTable *ThreadAGType) deleteItemChild2(mrQueryable mingru.Queryable, id uint64) error {
	return UserStats.UpdateThreadCount(mrQueryable, id, -1)
}

func (mrTable *ThreadAGType) DeleteItem(db *sql.DB, id uint64, userID uint64) error {
	txErr := mingru.Transact(db, func(tx *sql.Tx) error {
		var err error
		err = mrTable.deleteItemChild1(tx, id, userID)
		if err != nil {
			return err
		}
		err = mrTable.deleteItemChild2(tx, userID)
		if err != nil {
			return err
		}
		return nil
	})
	return txErr
}

func (mrTable *ThreadAGType) EditItem(mrQueryable mingru.Queryable, id uint64, userID uint64, contentHTML string, title string, sanitizedStub int) error {
	result, err := mrQueryable.Exec("UPDATE `thread` SET `modified_at` = NOW(3), `content` = ?, `title` = ? WHERE (`id` = ? AND `user_id` = ?)", contentHTML, title, id, userID)
	return mingru.CheckOneRowAffectedWithError(result, err)
}

func (mrTable *ThreadAGType) insertItemChild1(mrQueryable mingru.Queryable, userID uint64, contentHTML string, title string, forumID *uint64) (uint64, error) {
	result, err := mrQueryable.Exec("INSERT INTO `thread` (`created_at`, `cmt_count`, `likes`, `msg_count`, `last_replied_at`, `user_id`, `content`, `title`, `forum_id`, `modified_at`) VALUES (NOW(3), 0, 0, 0, NULL, ?, ?, ?, ?, `created_at`)", userID, contentHTML, title, forumID)
	return mingru.GetLastInsertIDUint64WithError(result, err)
}

func (mrTable *ThreadAGType) insertItemChild2(mrQueryable mingru.Queryable, id uint64) error {
	return UserStats.UpdateThreadCount(mrQueryable, id, 1)
}

func (mrTable *ThreadAGType) InsertItem(db *sql.DB, userID uint64, contentHTML string, title string, forumID *uint64, sanitizedStub int, captStub int) (uint64, error) {
	var insertedIDExported uint64
	txErr := mingru.Transact(db, func(tx *sql.Tx) error {
		var err error
		insertedID, err := mrTable.insertItemChild1(tx, userID, contentHTML, title, forumID)
		if err != nil {
			return err
		}
		err = mrTable.insertItemChild2(tx, userID)
		if err != nil {
			return err
		}
		insertedIDExported = insertedID
		return nil
	})
	return insertedIDExported, txErr
}

type ThreadAGSelectItemByIDResult struct {
	CmtCount      uint      `json:"cmtCount,omitempty"`
	ContentHTML   string    `json:"contentHTML,omitempty"`
	ForumID       *uint64   `json:"forumID,omitempty"`
	ID            uint64    `json:"-"`
	Likes         uint      `json:"likes,omitempty"`
	MsgCount      uint      `json:"msgCount,omitempty"`
	RawCreatedAt  time.Time `json:"-"`
	RawModifiedAt time.Time `json:"-"`
	Title         string    `json:"title,omitempty"`
	UserIconName  string    `json:"-"`
	UserID        uint64    `json:"-"`
	UserName      string    `json:"-"`
}

func (mrTable *ThreadAGType) SelectItemByID(mrQueryable mingru.Queryable, id uint64) (ThreadAGSelectItemByIDResult, error) {
	var result ThreadAGSelectItemByIDResult
	err := mrQueryable.QueryRow("SELECT `thread`.`id`, `thread`.`user_id`, `join_1`.`name`, `join_1`.`icon_name`, `thread`.`created_at`, `thread`.`modified_at`, `thread`.`content`, `thread`.`likes`, `thread`.`cmt_count`, `thread`.`title`, `thread`.`msg_count`, `thread`.`forum_id` FROM `thread` AS `thread` INNER JOIN `user` AS `join_1` ON `join_1`.`id` = `thread`.`user_id` WHERE `thread`.`id` = ?", id).Scan(&result.ID, &result.UserID, &result.UserName, &result.UserIconName, &result.RawCreatedAt, &result.RawModifiedAt, &result.ContentHTML, &result.Likes, &result.CmtCount, &result.Title, &result.MsgCount, &result.ForumID)
	if err != nil {
		return result, err
	}
	return result, nil
}

type ThreadAGSelectItemsForPostCenterOrderBy1 int

const (
	ThreadAGSelectItemsForPostCenterOrderBy1CreatedAt ThreadAGSelectItemsForPostCenterOrderBy1 = iota
	ThreadAGSelectItemsForPostCenterOrderBy1Likes
	ThreadAGSelectItemsForPostCenterOrderBy1MsgCount
)

type ThreadAGSelectItemsForPostCenterResult struct {
	ID            uint64    `json:"-"`
	Likes         uint      `json:"likes,omitempty"`
	MsgCount      uint      `json:"msgCount,omitempty"`
	RawCreatedAt  time.Time `json:"-"`
	RawModifiedAt time.Time `json:"-"`
	Title         string    `json:"title,omitempty"`
}

func (mrTable *ThreadAGType) SelectItemsForPostCenter(mrQueryable mingru.Queryable, userID uint64, page int, pageSize int, orderBy1 ThreadAGSelectItemsForPostCenterOrderBy1, orderBy1Desc bool) ([]ThreadAGSelectItemsForPostCenterResult, bool, error) {
	var orderBy1SQL string
	switch orderBy1 {
	case ThreadAGSelectItemsForPostCenterOrderBy1CreatedAt:
		orderBy1SQL = "`created_at`"
	case ThreadAGSelectItemsForPostCenterOrderBy1Likes:
		orderBy1SQL = "`likes`"
	case ThreadAGSelectItemsForPostCenterOrderBy1MsgCount:
		orderBy1SQL = "`msg_count`"
	default:
		err := fmt.Errorf("unsupported value %v", orderBy1)
		return nil, false, err
	}
	if orderBy1Desc {
		orderBy1SQL += " DESC"
	}

	if page <= 0 {
		err := fmt.Errorf("invalid page %v", page)
		return nil, false, err
	}
	if pageSize <= 0 {
		err := fmt.Errorf("invalid page size %v", pageSize)
		return nil, false, err
	}
	limit := pageSize + 1
	offset := (page - 1) * pageSize
	max := pageSize
	rows, err := mrQueryable.Query("SELECT `id`, `created_at`, `modified_at`, `likes`, `title`, `msg_count` FROM `thread` WHERE `user_id` = ? ORDER BY "+orderBy1SQL+" LIMIT ? OFFSET ?", userID, limit, offset)
	if err != nil {
		return nil, false, err
	}
	result := make([]ThreadAGSelectItemsForPostCenterResult, 0, limit)
	itemCounter := 0
	defer rows.Close()
	for rows.Next() {
		itemCounter++
		if itemCounter <= max {
			var item ThreadAGSelectItemsForPostCenterResult
			err = rows.Scan(&item.ID, &item.RawCreatedAt, &item.RawModifiedAt, &item.Likes, &item.Title, &item.MsgCount)
			if err != nil {
				return nil, false, err
			}
			result = append(result, item)
		}
	}
	err = rows.Err()
	if err != nil {
		return nil, false, err
	}
	return result, itemCounter > len(result), nil
}

type ThreadAGSelectItemsForUserProfileResult struct {
	ID            uint64    `json:"-"`
	MsgCount      uint      `json:"msgCount,omitempty"`
	RawCreatedAt  time.Time `json:"-"`
	RawModifiedAt time.Time `json:"-"`
	Title         string    `json:"title,omitempty"`
}

func (mrTable *ThreadAGType) SelectItemsForUserProfile(mrQueryable mingru.Queryable, userID uint64, page int, pageSize int) ([]ThreadAGSelectItemsForUserProfileResult, bool, error) {
	if page <= 0 {
		err := fmt.Errorf("invalid page %v", page)
		return nil, false, err
	}
	if pageSize <= 0 {
		err := fmt.Errorf("invalid page size %v", pageSize)
		return nil, false, err
	}
	limit := pageSize + 1
	offset := (page - 1) * pageSize
	max := pageSize
	rows, err := mrQueryable.Query("SELECT `id`, `created_at`, `modified_at`, `title`, `msg_count` FROM `thread` WHERE `user_id` = ? ORDER BY `created_at` DESC LIMIT ? OFFSET ?", userID, limit, offset)
	if err != nil {
		return nil, false, err
	}
	result := make([]ThreadAGSelectItemsForUserProfileResult, 0, limit)
	itemCounter := 0
	defer rows.Close()
	for rows.Next() {
		itemCounter++
		if itemCounter <= max {
			var item ThreadAGSelectItemsForUserProfileResult
			err = rows.Scan(&item.ID, &item.RawCreatedAt, &item.RawModifiedAt, &item.Title, &item.MsgCount)
			if err != nil {
				return nil, false, err
			}
			result = append(result, item)
		}
	}
	err = rows.Err()
	if err != nil {
		return nil, false, err
	}
	return result, itemCounter > len(result), nil
}

func (mrTable *ThreadAGType) SelectItemSrc(mrQueryable mingru.Queryable, id uint64, userID uint64) (EntityGetSrcResult, error) {
	var result EntityGetSrcResult
	err := mrQueryable.QueryRow("SELECT `content`, `title` FROM `thread` WHERE (`id` = ? AND `user_id` = ?)", id, userID).Scan(&result.ContentHTML, &result.Title)
	if err != nil {
		return result, err
	}
	return result, nil
}

func (mrTable *ThreadAGType) TestUpdateDates(mrQueryable mingru.Queryable, id uint64, rawCreatedAt time.Time, rawModifiedAt time.Time) error {
	result, err := mrQueryable.Exec("UPDATE `thread` SET `created_at` = ?, `modified_at` = ? WHERE `id` = ?", rawCreatedAt, rawModifiedAt, id)
	return mingru.CheckOneRowAffectedWithError(result, err)
}

func (mrTable *ThreadAGType) UpdateMsgCount(mrQueryable mingru.Queryable, id uint64, offset int) error {
	result, err := mrQueryable.Exec("UPDATE `thread` SET `msg_count` = `msg_count` + ? WHERE `id` = ?", offset, id)
	return mingru.CheckOneRowAffectedWithError(result, err)
}
