/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

 /******************************************************************************************
 * This file was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import (
	"database/sql"
	"fmt"
	"time"

	"github.com/mgenware/mingru-go-lib"
)

type TableTypeThreadMsg struct {
}

var ThreadMsg = &TableTypeThreadMsg{}

// MingruSQLName returns the name of this table.
func (mrTable *TableTypeThreadMsg) MingruSQLName() string {
	return "thread_msg"
}

// ------------ Actions ------------

func (mrTable *TableTypeThreadMsg) deleteItemChild1(mrQueryable mingru.Queryable, id uint64, userID uint64) error {
	result, err := mrQueryable.Exec("DELETE FROM `thread_msg` WHERE (`id` = ? AND `user_id` = ?)", id, userID)
	return mingru.CheckOneRowAffectedWithError(result, err)
}

func (mrTable *TableTypeThreadMsg) deleteItemChild2(mrQueryable mingru.Queryable, id uint64) error {
	return UserStats.UpdateThreadMsgCount(mrQueryable, id, -1)
}

func (mrTable *TableTypeThreadMsg) DeleteItem(db *sql.DB, id uint64, userID uint64) error {
	txErr := mingru.Transact(db, func(tx *sql.Tx) error {
		var err error
		err = mrTable.deleteItemChild1(tx, id, userID)
		if err != nil {
			return err
		}
		err = mrTable.deleteItemChild2(tx, id)
		if err != nil {
			return err
		}
		return nil
	})
	return txErr
}

func (mrTable *TableTypeThreadMsg) EditItem(mrQueryable mingru.Queryable, id uint64, userID uint64, threadID uint64, rawModifiedAt time.Time, sanitizedStub int) error {
	result, err := mrQueryable.Exec("UPDATE `thread_msg` SET `thread_id` = ?, `modified_at` = ? WHERE (`id` = ? AND `user_id` = ?)", threadID, rawModifiedAt, id, userID)
	return mingru.CheckOneRowAffectedWithError(result, err)
}

func (mrTable *TableTypeThreadMsg) insertItemChild1(mrQueryable mingru.Queryable, threadID uint64, userID uint64, contentHTML string, rawCreatedAt time.Time, rawModifiedAt time.Time) (uint64, error) {
	result, err := mrQueryable.Exec("INSERT INTO `thread_msg` (`thread_id`, `user_id`, `content`, `created_at`, `modified_at`, `cmt_count`, `likes`) VALUES (?, ?, ?, ?, ?, 0, 0)", threadID, userID, contentHTML, rawCreatedAt, rawModifiedAt)
	return mingru.GetLastInsertIDUint64WithError(result, err)
}

func (mrTable *TableTypeThreadMsg) insertItemChild2(mrQueryable mingru.Queryable, id uint64) error {
	return UserStats.UpdateThreadMsgCount(mrQueryable, id, 1)
}

func (mrTable *TableTypeThreadMsg) InsertItem(db *sql.DB, threadID uint64, userID uint64, contentHTML string, rawCreatedAt time.Time, rawModifiedAt time.Time, id uint64, sanitizedStub int, captStub int) (uint64, error) {
	var insertedIDExported uint64
	txErr := mingru.Transact(db, func(tx *sql.Tx) error {
		var err error
		insertedID, err := mrTable.insertItemChild1(tx, threadID, userID, contentHTML, rawCreatedAt, rawModifiedAt)
		if err != nil {
			return err
		}
		err = mrTable.insertItemChild2(tx, id)
		if err != nil {
			return err
		}
		insertedIDExported = insertedID
		return nil
	})
	return insertedIDExported, txErr
}

type ThreadMsgTableSelectItemByIDResult struct {
	CmtCount      uint      `json:"cmtCount,omitempty"`
	ContentHTML   string    `json:"contentHTML,omitempty"`
	ID            uint64    `json:"-"`
	Likes         uint      `json:"likes,omitempty"`
	RawCreatedAt  time.Time `json:"-"`
	RawModifiedAt time.Time `json:"-"`
	ThreadID      uint64    `json:"threadID,omitempty"`
	UserIconName  string    `json:"-"`
	UserID        uint64    `json:"-"`
	UserName      string    `json:"-"`
}

func (mrTable *TableTypeThreadMsg) SelectItemByID(mrQueryable mingru.Queryable, id uint64) (ThreadMsgTableSelectItemByIDResult, error) {
	var result ThreadMsgTableSelectItemByIDResult
	err := mrQueryable.QueryRow("SELECT `thread_msg`.`id`, `thread_msg`.`user_id`, `join_1`.`name`, `join_1`.`icon_name`, `thread_msg`.`created_at`, `thread_msg`.`modified_at`, `thread_msg`.`content`, `thread_msg`.`likes`, `thread_msg`.`cmt_count`, `thread_msg`.`thread_id` FROM `thread_msg` AS `thread_msg` INNER JOIN `user` AS `join_1` ON `join_1`.`id` = `thread_msg`.`user_id` WHERE `thread_msg`.`id` = ?", id).Scan(&result.ID, &result.UserID, &result.UserName, &result.UserIconName, &result.RawCreatedAt, &result.RawModifiedAt, &result.ContentHTML, &result.Likes, &result.CmtCount, &result.ThreadID)
	if err != nil {
		return result, err
	}
	return result, nil
}

const (
	ThreadMsgTableSelectItemsForPostCenterOrderBy1CreatedAt = iota
	ThreadMsgTableSelectItemsForPostCenterOrderBy1Likes
	ThreadMsgTableSelectItemsForPostCenterOrderBy1CmtCount
)

type ThreadMsgTableSelectItemsForPostCenterResult struct {
	ID            uint64    `json:"-"`
	Likes         uint      `json:"likes,omitempty"`
	RawCreatedAt  time.Time `json:"-"`
	RawModifiedAt time.Time `json:"-"`
	ThreadID      uint64    `json:"threadID,omitempty"`
}

func (mrTable *TableTypeThreadMsg) SelectItemsForPostCenter(mrQueryable mingru.Queryable, userID uint64, page int, pageSize int, orderBy1 int, orderBy1Desc bool) ([]ThreadMsgTableSelectItemsForPostCenterResult, bool, error) {
	var orderBy1SQL string
	switch orderBy1 {
	case ThreadMsgTableSelectItemsForPostCenterOrderBy1CreatedAt:
		orderBy1SQL = "`created_at`"
	case ThreadMsgTableSelectItemsForPostCenterOrderBy1Likes:
		orderBy1SQL = "`likes`"
	case ThreadMsgTableSelectItemsForPostCenterOrderBy1CmtCount:
		orderBy1SQL = "`cmt_count`"
	default:
		err := fmt.Errorf("Unsupported value %v", orderBy1)
		return nil, false, err
	}
	if orderBy1Desc {
		orderBy1SQL += " DESC"
	}

	if page <= 0 {
		err := fmt.Errorf("Invalid page %v", page)
		return nil, false, err
	}
	if pageSize <= 0 {
		err := fmt.Errorf("Invalid page size %v", pageSize)
		return nil, false, err
	}
	limit := pageSize + 1
	offset := (page - 1) * pageSize
	max := pageSize
	rows, err := mrQueryable.Query("SELECT `id`, `created_at`, `modified_at`, `likes`, `thread_id` FROM `thread_msg` WHERE `user_id` = ? ORDER BY "+orderBy1SQL+" LIMIT ? OFFSET ?", userID, limit, offset)
	if err != nil {
		return nil, false, err
	}
	result := make([]ThreadMsgTableSelectItemsForPostCenterResult, 0, limit)
	itemCounter := 0
	defer rows.Close()
	for rows.Next() {
		itemCounter++
		if itemCounter <= max {
			var item ThreadMsgTableSelectItemsForPostCenterResult
			err = rows.Scan(&item.ID, &item.RawCreatedAt, &item.RawModifiedAt, &item.Likes, &item.ThreadID)
			if err != nil {
				return nil, false, err
			}
			result = append(result, item)
		}
	}
	err = rows.Err()
	if err != nil {
		return nil, false, err
	}
	return result, itemCounter > len(result), nil
}

type ThreadMsgTableSelectItemsForUserProfileResult struct {
	ID            uint64    `json:"-"`
	RawCreatedAt  time.Time `json:"-"`
	RawModifiedAt time.Time `json:"-"`
	ThreadID      uint64    `json:"threadID,omitempty"`
}

func (mrTable *TableTypeThreadMsg) SelectItemsForUserProfile(mrQueryable mingru.Queryable, userID uint64, page int, pageSize int) ([]ThreadMsgTableSelectItemsForUserProfileResult, bool, error) {
	if page <= 0 {
		err := fmt.Errorf("Invalid page %v", page)
		return nil, false, err
	}
	if pageSize <= 0 {
		err := fmt.Errorf("Invalid page size %v", pageSize)
		return nil, false, err
	}
	limit := pageSize + 1
	offset := (page - 1) * pageSize
	max := pageSize
	rows, err := mrQueryable.Query("SELECT `id`, `created_at`, `modified_at`, `thread_id` FROM `thread_msg` WHERE `user_id` = ? ORDER BY `created_at` DESC LIMIT ? OFFSET ?", userID, limit, offset)
	if err != nil {
		return nil, false, err
	}
	result := make([]ThreadMsgTableSelectItemsForUserProfileResult, 0, limit)
	itemCounter := 0
	defer rows.Close()
	for rows.Next() {
		itemCounter++
		if itemCounter <= max {
			var item ThreadMsgTableSelectItemsForUserProfileResult
			err = rows.Scan(&item.ID, &item.RawCreatedAt, &item.RawModifiedAt, &item.ThreadID)
			if err != nil {
				return nil, false, err
			}
			result = append(result, item)
		}
	}
	err = rows.Err()
	if err != nil {
		return nil, false, err
	}
	return result, itemCounter > len(result), nil
}

func (mrTable *TableTypeThreadMsg) SelectItemSrc(mrQueryable mingru.Queryable, id uint64, userID uint64) (EntityGetSrcResult, error) {
	var result EntityGetSrcResult
	err := mrQueryable.QueryRow("SELECT `content`, `thread_id` FROM `thread_msg` WHERE (`id` = ? AND `user_id` = ?)", id, userID).Scan(&result.ContentHTML, &result.ThreadID)
	if err != nil {
		return result, err
	}
	return result, nil
}

func (mrTable *TableTypeThreadMsg) SelectMsgsByThread(mrQueryable mingru.Queryable, threadID uint64, page int, pageSize int) ([]ThreadMsgResult, bool, error) {
	if page <= 0 {
		err := fmt.Errorf("Invalid page %v", page)
		return nil, false, err
	}
	if pageSize <= 0 {
		err := fmt.Errorf("Invalid page size %v", pageSize)
		return nil, false, err
	}
	limit := pageSize + 1
	offset := (page - 1) * pageSize
	max := pageSize
	rows, err := mrQueryable.Query("SELECT `thread_msg`.`id`, `thread_msg`.`user_id`, `join_1`.`name`, `join_1`.`icon_name`, `thread_msg`.`created_at`, `thread_msg`.`modified_at`, `thread_msg`.`content`, `thread_msg`.`likes`, `thread_msg`.`cmt_count`, `thread_msg`.`thread_id` FROM `thread_msg` AS `thread_msg` INNER JOIN `user` AS `join_1` ON `join_1`.`id` = `thread_msg`.`user_id` WHERE `thread_msg`.`thread_id` = ? ORDER BY `thread_msg`.`likes` LIMIT ? OFFSET ?", threadID, limit, offset)
	if err != nil {
		return nil, false, err
	}
	result := make([]ThreadMsgResult, 0, limit)
	itemCounter := 0
	defer rows.Close()
	for rows.Next() {
		itemCounter++
		if itemCounter <= max {
			var item ThreadMsgResult
			err = rows.Scan(&item.ID, &item.UserID, &item.UserName, &item.UserIconName, &item.RawCreatedAt, &item.RawModifiedAt, &item.ContentHTML, &item.Likes, &item.CmtCount, &item.ThreadID)
			if err != nil {
				return nil, false, err
			}
			result = append(result, item)
		}
	}
	err = rows.Err()
	if err != nil {
		return nil, false, err
	}
	return result, itemCounter > len(result), nil
}

func (mrTable *TableTypeThreadMsg) SelectMsgsByThreadWithLikes(mrQueryable mingru.Queryable, viewerUserID uint64, threadID uint64, page int, pageSize int) ([]ThreadMsgResult, bool, error) {
	if page <= 0 {
		err := fmt.Errorf("Invalid page %v", page)
		return nil, false, err
	}
	if pageSize <= 0 {
		err := fmt.Errorf("Invalid page size %v", pageSize)
		return nil, false, err
	}
	limit := pageSize + 1
	offset := (page - 1) * pageSize
	max := pageSize
	rows, err := mrQueryable.Query("SELECT `thread_msg`.`id`, `thread_msg`.`user_id`, `join_1`.`name`, `join_1`.`icon_name`, `thread_msg`.`created_at`, `thread_msg`.`modified_at`, `thread_msg`.`content`, `thread_msg`.`likes`, `thread_msg`.`cmt_count`, `thread_msg`.`thread_id`, `join_2`.`user_id` AS `is_liked` FROM `thread_msg` AS `thread_msg` INNER JOIN `user` AS `join_1` ON `join_1`.`id` = `thread_msg`.`user_id` LEFT JOIN `thread_msg_like` AS `join_2` ON `join_2`.`host_id` = `thread_msg`.`id` AND `join_2`.`user_id` = ? WHERE `thread_msg`.`thread_id` = ? ORDER BY `thread_msg`.`likes` LIMIT ? OFFSET ?", viewerUserID, threadID, limit, offset)
	if err != nil {
		return nil, false, err
	}
	result := make([]ThreadMsgResult, 0, limit)
	itemCounter := 0
	defer rows.Close()
	for rows.Next() {
		itemCounter++
		if itemCounter <= max {
			var item ThreadMsgResult
			err = rows.Scan(&item.ID, &item.UserID, &item.UserName, &item.UserIconName, &item.RawCreatedAt, &item.RawModifiedAt, &item.ContentHTML, &item.Likes, &item.CmtCount, &item.ThreadID, &item.IsLiked)
			if err != nil {
				return nil, false, err
			}
			result = append(result, item)
		}
	}
	err = rows.Err()
	if err != nil {
		return nil, false, err
	}
	return result, itemCounter > len(result), nil
}

func (mrTable *TableTypeThreadMsg) TestUpdateDates(mrQueryable mingru.Queryable, id uint64, rawCreatedAt time.Time, rawModifiedAt time.Time) error {
	result, err := mrQueryable.Exec("UPDATE `thread_msg` SET `created_at` = ?, `modified_at` = ? WHERE `id` = ?", rawCreatedAt, rawModifiedAt, id)
	return mingru.CheckOneRowAffectedWithError(result, err)
}
