 /******************************************************************************************
 * This code was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import (
	"github.com/mgenware/go-packagex/v5/dbx"
)

// TableTypeUserPwd ...
type TableTypeUserPwd struct {
}

// UserPwd ...
var UserPwd = &TableTypeUserPwd{}

// ------------ Actions ------------

// AddUserPwd ...
func (da *TableTypeUserPwd) AddUserPwd(queryable dbx.Queryable, pwdHash string) (uint64, error) {
	result, err := queryable.Exec("INSERT INTO `user_pwd` (`pwd_hash`) VALUES (?)", pwdHash)
	return dbx.GetLastInsertIDUint64WithError(result, err)
}
