 /******************************************************************************************
 * This code was automatically generated by mingru (https://github.com/mgenware/mingru)
 * Do not edit this file manually, your changes will be overwritten.
 ******************************************************************************************/

package da

import (
	"github.com/mgenware/go-packagex/v5/dbx"
)

// TableTypeUserAuth ...
type TableTypeUserAuth struct {
}

// UserAuth ...
var UserAuth = &TableTypeUserAuth{}

// ------------ Actions ------------

// AddUserAuth ...
func (da *TableTypeUserAuth) AddUserAuth(queryable dbx.Queryable, authType uint16) (uint64, error) {
	result, err := queryable.Exec("INSERT INTO `user_auth` (`auth_type`) VALUES (?)", authType)
	return dbx.GetLastInsertIDUint64WithError(result, err)
}
