/*
 * Copyright (C) 2019 The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that can be
 * found in the LICENSE file.
 */

/* eslint-disable */

/******************************************************************************************
* This code was automatically generated by json-to-js-const.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/

export const maxTitleLen = 200;
export const maxEmailLen = 200;
export const maxNameLen = 100;
export const maxFileNameLen = 255;
export const maxUserStatusLen = 200;
export const maxUserInfoFieldLen = 100;
export const maxURLLen = 200;
export const maxPwdHashLen = 255;
