/* eslint-disable */

/******************************************************************************************
* This code was automatically generated by json-to-js-const.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/

export const maxTitleLen = 200;
export const maxEmailLen = 200;
export const maxNameLen = 100;
export const maxFileNameLen = 255;
export const maxUserStatusLen = 200;
export const maxUserInfoFieldLen = 100;
export const maxURLLen = 200;
export const maxPwdHashLen = 255;
