/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

/******************************************************************************************
 * Do not edit this file manually.
 * Automatically generated via `qing sod mx`.
 * See `lib/dev/sod/objects/mx.yaml` for details.
 ******************************************************************************************/

package mxSod

type SiteSettingsBase struct {
	NeedRestart bool `json:"needRestart,omitempty"`
}

func NewSiteSettingsBase(needRestart bool) SiteSettingsBase {
	return SiteSettingsBase{
		NeedRestart: needRestart,
	}
}

type SiteGenSettings struct {
	SiteSettingsBase

	SiteType int `json:"siteType,omitempty"`
}

func NewSiteGenSettings(siteSettingsBase *SiteSettingsBase, siteType int) SiteGenSettings {
	return SiteGenSettings{
		SiteSettingsBase: *siteSettingsBase,
		SiteType: siteType,
	}
}
