/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

/* eslint-disable */

 /******************************************************************************************
  * Do not edit this file manually.
  * Automatically generated via `qing sod thread/threadWind`.
  * See `lib/dev/sod/objects/thread/threadWind.yaml` for details.
  ******************************************************************************************/

export interface ThreadWind {
  threadID: string;
  forumID: string;
}
