/*
* Copyright (C) The Qing Project. All rights reserved.
*
* Use of this source code is governed by a license that
* can be found in the LICENSE file.
*/

 /******************************************************************************************
* This code was automatically generated by `@qing/def`.
* Do not edit this file manually, your changes will be overwritten.
******************************************************************************************/

package frozenDef

type ContentBaseType int

const (
	ContentBaseTypePost ContentBaseType = iota + 1
	ContentBaseTypeCmt
	ContentBaseTypeFPost
)

type DbDelFlags int

const (
	DbDelFlagsSelf DbDelFlags = iota + 1
	DbDelFlagsHost
)

type ContentInputTypeConfig string

const (
	ContentInputTypeConfigStandard ContentInputTypeConfig = "standard"
	ContentInputTypeConfigMarkdown = "markdown"
)

type PostPermissionConfig string

const (
	PostPermissionConfigOnlyMe PostPermissionConfig = "onlyMe"
	PostPermissionConfigEveryone = "everyone"
)
