/*
 * Copyright (C) The Qing Project. All rights reserved.
 *
 * Use of this source code is governed by a license that
 * can be found in the LICENSE file.
 */

/* eslint-disable */

 /******************************************************************************************
  * Do not edit this file manually.
  * Automatically generated via `qing sod contentBase/contentBaseModelBase`.
  * See `lib/dev/sod/objects/contentBase/contentBaseModelBase.yaml` for details.
  ******************************************************************************************/

export interface ContentBaseModelBase {
  url: string;
  userURL: string;
  userIconURL: string;
  createdAt: string;
  modifiedAt: string;
}
